volumes:
   gitb-repo:
   gitb-dbdata:

services:
   gitb-redis:
      build:
        context: ./etc/docker/gitb-redis
      restart: unless-stopped
   gitb-postgresql:
      build:
        context: etc/docker/gitb-postgresql
      restart: unless-stopped
      volumes:
       - gitb-dbdata:/var/lib/postgresql/data
      healthcheck:
       test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
       interval: 3s
       retries: 10
   gitb-srv:
      build:
        context: ./
        dockerfile: etc/docker/build/Dockerfile-srv
      restart: unless-stopped
      environment:
       - CALLBACK_ROOT_URL=http://localhost:8080/itbsrv
      ports:
       - "8080:8080"
   gitb-ui:
      build:
        context: ./
        dockerfile: etc/docker/build/Dockerfile-ui   
      restart: unless-stopped
      ports:
       - "9000:9000"
      volumes:
       - gitb-repo:/gitb-repository
      depends_on:
       gitb-redis:
         condition: service_started
       gitb-postgresql:
         condition: service_healthy
       gitb-srv:
         condition: service_started 