--
-- table `domains`
--

CREATE TABLE "Domains" (
                           id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                           sname varchar(254) NOT NULL,
                           fname varchar(254) NOT NULL,
                           api_key varchar(254) NOT NULL,
                           description text,
                           report_metadata text,
                           PRIMARY KEY (id),
                           CONSTRAINT dom_unique_api_key UNIQUE  (api_key)
) ;

CREATE INDEX dom_idx_api_key ON "Domains" (api_key);

--
-- table `SpecificationGroups`
--

CREATE TABLE "SpecificationGroups" (
                                       id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                       sname varchar(254) NOT NULL,
                                       fname varchar(254) NOT NULL,
                                       api_key varchar(255) NOT NULL,
                                       description text,
                                       report_metadata text,
                                       domain bigint NOT NULL,
                                       display_order smallint NOT NULL DEFAULT 0,
                                       PRIMARY KEY (id),
                                       CONSTRAINT specgroup_unique_api_key UNIQUE  (api_key)
    ,
                                       CONSTRAINT spec_group_fk_domain FOREIGN KEY (domain) REFERENCES "Domains"(id)
) ;

CREATE INDEX spec_idx_domain ON "SpecificationGroups" (domain);
CREATE INDEX sgroup_idx_api_key ON "SpecificationGroups" (api_key);

--
-- table `Specifications`
--

CREATE TABLE "Specifications" (
                                  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                  sname varchar(254) NOT NULL,
                                  fname varchar(254) NOT NULL,
                                  description text,
                                  report_metadata text,
                                  domain bigint NOT NULL,
                                  is_hidden boolean NOT NULL DEFAULT false,
                                  api_key varchar(255) NOT NULL,
                                  spec_group bigint DEFAULT NULL,
                                  display_order smallint NOT NULL DEFAULT 0,
                                  PRIMARY KEY (id),
                                  CONSTRAINT spec_unique_api_key UNIQUE  (api_key)
    ,
                                  CONSTRAINT spe_fk_dom FOREIGN KEY (domain) REFERENCES "Domains"(id),
                                  CONSTRAINT spec_fk_spec_group FOREIGN KEY (spec_group) REFERENCES "SpecificationGroups" (id)
) ;

CREATE INDEX spe_fk_dom ON "Specifications" (domain);
CREATE INDEX spe_idx_api_key ON "Specifications" (api_key);
CREATE INDEX spec_idx_spec_group ON "Specifications" (spec_group);

--
-- table `Actors`
--

CREATE TABLE "Actors" (
                          id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                          "actorId" varchar(254) NOT NULL,
                          name varchar(254) NOT NULL,
                          description text,
                          report_metadata text,
                          domain bigint NOT NULL,
                          is_default boolean NOT NULL DEFAULT false,
                          display_order smallint DEFAULT NULL,
                          is_hidden boolean NOT NULL DEFAULT false,
                          api_key varchar(255) NOT NULL,
                          PRIMARY KEY (id),
                          CONSTRAINT act_unique_api_key UNIQUE  (api_key)
    ,
                          CONSTRAINT ac_fk_dom FOREIGN KEY (domain) REFERENCES "Domains"(id)
) ;

CREATE INDEX ac_fk_dom ON "Actors" (domain);
CREATE INDEX act_idx_api_key ON "Actors" (api_key);

--
-- table `Endpoints`
--

CREATE TABLE "Endpoints" (
                             id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                             name varchar(254) NOT NULL,
                             description text,
                             actor bigint NOT NULL,
                             PRIMARY KEY (id),
                             CONSTRAINT endp_act_unq_idx UNIQUE (name,actor)
    ,
                             CONSTRAINT end_fk_act FOREIGN KEY (actor) REFERENCES "Actors"(id)
) ;

CREATE INDEX end_fk_act ON "Endpoints" (actor);

--
-- table `Communities`
--

CREATE TABLE "Communities" (
                               id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               sname varchar(254) NOT NULL,
                               fname varchar(254) NOT NULL,
                               domain bigint DEFAULT NULL,
                               support_email varchar(254) DEFAULT NULL,
                               selfreg_type smallint NOT NULL DEFAULT '1',
                               selfreg_token varchar(254) DEFAULT NULL,
                               selfreg_notification boolean NOT NULL DEFAULT false,
                               description text,
                               selfreg_restriction smallint NOT NULL DEFAULT '1',
                               selfreg_token_help_text text,
                               selfreg_force_template boolean NOT NULL DEFAULT false,
                               selfreg_force_properties boolean NOT NULL DEFAULT false,
                               allow_certificate_download boolean NOT NULL DEFAULT false,
                               allow_system_management boolean NOT NULL DEFAULT true,
                               allow_statement_management boolean NOT NULL DEFAULT true,
                               allow_post_test_org_updates boolean NOT NULL DEFAULT true,
                               allow_post_test_sys_updates boolean NOT NULL DEFAULT true,
                               allow_post_test_stm_updates boolean NOT NULL DEFAULT true,
                               allow_automation_api boolean NOT NULL DEFAULT false,
                               allow_community_view boolean NOT NULL DEFAULT false,
                               api_key varchar(255) NOT NULL,
                               interaction_notification boolean NOT NULL DEFAULT false,
                               latest_status_label varchar(254) DEFAULT NULL,
                               PRIMARY KEY (id),
                               CONSTRAINT com_unique_api_key UNIQUE  (api_key)
    ,
                               CONSTRAINT com_fk_dom FOREIGN KEY (domain) REFERENCES "Domains"(id)
) ;

CREATE INDEX com_fk_dom ON "Communities" (domain);
CREATE INDEX com_idx_api_key ON "Communities" (api_key);

INSERT INTO "Communities" VALUES (0,'Default community','Default community',NULL,NULL,1,NULL,false,NULL,1,NULL,false,false,false,true,true,true,true,true,false,false,'225D4900X6DA6X4479X9BBFX32B50FB1B916',false,NULL);
UPDATE "Communities" SET id = 0;

--
-- table `ConformanceSnapshots`
--

CREATE TABLE "ConformanceSnapshots" (
                                        id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                        label varchar(254) NOT NULL,
                                        snapshot_time timestamp(0) NOT NULL,
                                        community bigint NOT NULL,
                                        api_key varchar(254) NOT NULL,
                                        public_label varchar(254) DEFAULT NULL,
                                        is_public boolean NOT NULL DEFAULT false,
                                        PRIMARY KEY (id),
                                        CONSTRAINT consnap_unique_api_key UNIQUE  (api_key)
    ,
                                        CONSTRAINT conf_snap_fk_community FOREIGN KEY (community) REFERENCES "Communities"(id)
) ;

CREATE INDEX conf_snap_idx_community ON "ConformanceSnapshots" (community);
CREATE INDEX conf_snap_idx_api_key ON "ConformanceSnapshots" (api_key);

--
-- table `CommunityKeystores`
--

CREATE TABLE "CommunityKeystores" (
                                      id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                      keystore_file BYTEA NOT NULL,
                                      keystore_type varchar(255) NOT NULL,
                                      keystore_pass varchar(255) NOT NULL,
                                      key_pass varchar(255) NOT NULL,
                                      community bigint NOT NULL,
                                      PRIMARY KEY (id)
    ,
                                      CONSTRAINT cokey_fk_com FOREIGN KEY (community) REFERENCES "Communities"(id)
) ;

CREATE INDEX cokey_fk_com ON "CommunityKeystores" (community);

--
-- table `CommunityLabels`
--

CREATE TABLE "CommunityLabels" (
                                   community bigint NOT NULL,
                                   label_type smallint NOT NULL,
                                   singular_form varchar(254) NOT NULL,
                                   plural_form varchar(254) NOT NULL,
                                   fixed_case boolean NOT NULL DEFAULT false,
                                   PRIMARY KEY (community,label_type),
                                   CONSTRAINT cl_fk_com FOREIGN KEY (community) REFERENCES "Communities"(id)
) ;

--
-- table `CommunityResources`
--

CREATE TABLE "CommunityResources" (
                                      id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                      name varchar(254) NOT NULL,
                                      description text,
                                      community bigint NOT NULL,
                                      PRIMARY KEY (id),
                                      CONSTRAINT cr_com_name_idx UNIQUE  (name,community)
    ,
                                      CONSTRAINT cr_fk_com FOREIGN KEY (community) REFERENCES "Communities"(id)
) ;

CREATE INDEX cr_fk_com ON "CommunityResources" (community);

--
-- table `ConformanceCertificates`
--

CREATE TABLE "ConformanceCertificates" (
                                           id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 2),
                                           title varchar(255) DEFAULT NULL,
                                           message text,
                                           include_message boolean NOT NULL DEFAULT false,
                                           include_test_status boolean NOT NULL DEFAULT false,
                                           include_test_cases boolean NOT NULL DEFAULT false,
                                           include_details boolean NOT NULL DEFAULT false,
                                           include_signature boolean NOT NULL DEFAULT false,
                                           community bigint NOT NULL,
                                           include_title boolean NOT NULL DEFAULT true,
                                           include_page_numbers boolean NOT NULL DEFAULT true,
                                           PRIMARY KEY (id),
                                           CONSTRAINT cs_co_id_idx UNIQUE (community),
                                           CONSTRAINT ccert_fk_com FOREIGN KEY (community) REFERENCES "Communities"(id)
)  ;

INSERT INTO "ConformanceCertificates" VALUES (1,'Conformance Certificate',NULL,false,true,true,true,false,0,true,true);

--
-- table `ConformanceOverviewCertificateMessages`
--

CREATE TABLE "ConformanceOverviewCertificateMessages" (
                                                          id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                          message_type smallint NOT NULL,
                                                          message text NOT NULL,
                                                          domain_id bigint DEFAULT NULL,
                                                          group_id bigint DEFAULT NULL,
                                                          specification_id bigint DEFAULT NULL,
                                                          actor_id bigint DEFAULT NULL,
                                                          community_id bigint NOT NULL,
                                                          PRIMARY KEY (id)
    ,
                                                          CONSTRAINT cocertmsg_fk_act FOREIGN KEY (actor_id) REFERENCES "Actors"(id),
                                                          CONSTRAINT cocertmsg_fk_com FOREIGN KEY (community_id) REFERENCES "Communities"(id),
                                                          CONSTRAINT cocertmsg_fk_dom FOREIGN KEY (domain_id) REFERENCES "Domains"(id),
                                                          CONSTRAINT cocertmsg_fk_spe FOREIGN KEY (specification_id) REFERENCES "Specifications"(id),
                                                          CONSTRAINT cocertmsg_fk_spg FOREIGN KEY (group_id) REFERENCES "SpecificationGroups" (id)
) ;

CREATE INDEX cocertmsg_fk_dom ON "ConformanceOverviewCertificateMessages" (domain_id);
CREATE INDEX cocertmsg_fk_spg ON "ConformanceOverviewCertificateMessages" (group_id);
CREATE INDEX cocertmsg_fk_spe ON "ConformanceOverviewCertificateMessages" (specification_id);
CREATE INDEX cocertmsg_fk_act ON "ConformanceOverviewCertificateMessages" (actor_id);
CREATE INDEX cocertmsg_fk_com ON "ConformanceOverviewCertificateMessages" (community_id);

--
-- table `conformanceoverviewcertificates`
--

CREATE TABLE "ConformanceOverviewCertificates" (
                                                   id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                   title varchar(255) DEFAULT NULL,
                                                   message text,
                                                   include_message boolean NOT NULL DEFAULT false,
                                                   include_statement_status boolean NOT NULL DEFAULT false,
                                                   include_statements boolean NOT NULL DEFAULT false,
                                                   include_statement_details boolean NOT NULL DEFAULT false,
                                                   include_details boolean NOT NULL DEFAULT false,
                                                   include_signature boolean NOT NULL DEFAULT false,
                                                   include_title boolean NOT NULL DEFAULT true,
                                                   include_page_numbers boolean NOT NULL DEFAULT true,
                                                   enable_all boolean NOT NULL DEFAULT false,
                                                   enable_domain boolean NOT NULL DEFAULT false,
                                                   enable_group boolean NOT NULL DEFAULT false,
                                                   enable_specification boolean NOT NULL DEFAULT false,
                                                   community bigint NOT NULL,
                                                   PRIMARY KEY (id),
                                                   CONSTRAINT cos_co_id_idx UNIQUE (community),
                                                   CONSTRAINT cocert_fk_com FOREIGN KEY (community) REFERENCES "Communities"(id)
) ;

--
-- table `conformancesnapshotActors`
--

CREATE TABLE "ConformanceSnapshotActors" (
                                             id bigint NOT NULL,
                                             actorId varchar(254) NOT NULL,
                                             name varchar(254) NOT NULL,
                                             description text,
                                             report_metadata text,
                                             api_key varchar(255) NOT NULL,
                                             snapshot_id bigint NOT NULL,
                                             visible boolean NOT NULL DEFAULT false,
                                             PRIMARY KEY (id,snapshot_id)
    ,
                                             CONSTRAINT cs_ac_fk_cs FOREIGN KEY (snapshot_id) REFERENCES "ConformanceSnapshots"(id)
) ;

CREATE INDEX cs_ac_id ON "ConformanceSnapshotActors"  (id);
CREATE INDEX cs_ac_fk_cs ON "ConformanceSnapshotActors"  (snapshot_id);

--
-- table `conformancesnapshotcertificatemessages`
--

CREATE TABLE "conformancesnapshotcertificatemessages" (
                                                          snapshot_id bigint NOT NULL,
                                                          message text NOT NULL,
                                                          PRIMARY KEY (snapshot_id),
                                                          CONSTRAINT cs_cert_msg_cs_fk FOREIGN KEY (snapshot_id) REFERENCES "ConformanceSnapshots"(id)
) ;

--
-- table `conformancesnapshotdomainparams`
--

CREATE TABLE "conformancesnapshotdomainparams" (
                                                   domain_id bigint NOT NULL,
                                                   snapshot_id bigint NOT NULL,
                                                   param_key varchar(254) NOT NULL,
                                                   param_value varchar(254) NOT NULL,
                                                   PRIMARY KEY (domain_id,snapshot_id,param_key)
    ,
                                                   CONSTRAINT cs_dom_param_cs_fk FOREIGN KEY (snapshot_id) REFERENCES "ConformanceSnapshots"(id)
) ;

CREATE INDEX cs_dom_param_cs_domain_idx ON "conformancesnapshotdomainparams" (domain_id);
CREATE INDEX cs_dom_param_cs_snapshot_idx ON "conformancesnapshotdomainparams" (snapshot_id);

--
-- table `conformancesnapshotDomains`
--

CREATE TABLE "ConformanceSnapshotDomains" (
                                              id bigint NOT NULL,
                                              sname varchar(254) NOT NULL,
                                              fname varchar(254) NOT NULL,
                                              description text,
                                              report_metadata text,
                                              snapshot_id bigint NOT NULL,
                                              PRIMARY KEY (id,snapshot_id)
    ,
                                              CONSTRAINT cs_dom_fk_cs FOREIGN KEY (snapshot_id) REFERENCES "ConformanceSnapshots"(id)
) ;

CREATE INDEX cs_dom_id ON "ConformanceSnapshotDomains"  (id);
CREATE INDEX cs_dom_fk_cs ON "ConformanceSnapshotDomains"  (snapshot_id);

--
-- table `conformancesnapshotorganisations`
--

CREATE TABLE "ConformanceSnapshotOrganisations" (
                                                    id bigint NOT NULL,
                                                    sname varchar(254) NOT NULL,
                                                    fname varchar(254) NOT NULL,
                                                    api_key varchar(254) DEFAULT NULL,
                                                    snapshot_id bigint NOT NULL,
                                                    PRIMARY KEY (id,snapshot_id)
    ,
                                                    CONSTRAINT cs_org_fk_cs FOREIGN KEY (snapshot_id) REFERENCES "ConformanceSnapshots"(id)
) ;

CREATE INDEX cs_org_id ON "ConformanceSnapshotOrganisations" (id);
CREATE INDEX cs_org_fk_cs ON "ConformanceSnapshotOrganisations" (snapshot_id);

--
-- table `conformancesnapshotorgparams`
--

CREATE TABLE "conformancesnapshotorgparams" (
                                                org_id bigint NOT NULL,
                                                snapshot_id bigint NOT NULL,
                                                param_key varchar(254) NOT NULL,
                                                param_value varchar(254) NOT NULL,
                                                PRIMARY KEY (org_id,snapshot_id,param_key)
    ,
                                                CONSTRAINT cs_org_param_cs_fk FOREIGN KEY (snapshot_id) REFERENCES "ConformanceSnapshots"(id)
) ;

CREATE INDEX cs_org_param_cs_org_idx ON "conformancesnapshotorgparams" (org_id);
CREATE INDEX cs_org_param_cs_snapshot_idx ON "conformancesnapshotorgparams" (snapshot_id);

--
-- table `conformancesnapshotoverviewcertificatemessages`
--

CREATE TABLE "conformancesnapshotoverviewcertificatemessages" (
                                                                  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                                  snapshot_id bigint NOT NULL,
                                                                  message_type smallint NOT NULL,
                                                                  message text NOT NULL,
                                                                  domain_id bigint DEFAULT NULL,
                                                                  group_id bigint DEFAULT NULL,
                                                                  specification_id bigint DEFAULT NULL,
                                                                  actor_id bigint DEFAULT NULL,
                                                                  PRIMARY KEY (id)
    ,
                                                                  CONSTRAINT cs_cert_over_msg_cs_fk FOREIGN KEY (snapshot_id) REFERENCES "ConformanceSnapshots"(id)
) ;

CREATE INDEX cs_cert_over_msg_cs_idx ON "conformancesnapshotoverviewcertificatemessages" (snapshot_id);

--
-- table `ConformanceSnapshotspecificationGroups`
--

CREATE TABLE "ConformanceSnapshotspecificationGroups" (
                                                          id bigint NOT NULL,
                                                          sname varchar(254) NOT NULL,
                                                          fname varchar(254) NOT NULL,
                                                          description text,
                                                          report_metadata text,
                                                          display_order smallint NOT NULL DEFAULT 0,
                                                          snapshot_id bigint NOT NULL,
                                                          PRIMARY KEY (id,snapshot_id)
    ,
                                                          CONSTRAINT cs_spg_fk_cs FOREIGN KEY (snapshot_id) REFERENCES "ConformanceSnapshots"(id)
) ;

CREATE INDEX cs_spg_id ON "ConformanceSnapshotspecificationGroups" (id);
CREATE INDEX cs_spg_fk_cs ON "ConformanceSnapshotspecificationGroups" (snapshot_id);

--
-- table `ConformanceSnapshotspecifications`
--

CREATE TABLE "ConformanceSnapshotSpecifications" (
                                                     id bigint NOT NULL,
                                                     sname varchar(254) NOT NULL,
                                                     fname varchar(254) NOT NULL,
                                                     description text,
                                                     report_metadata text,
                                                     display_order smallint NOT NULL DEFAULT 0,
                                                     api_key varchar(255) NOT NULL,
                                                     snapshot_id bigint NOT NULL,
                                                     PRIMARY KEY (id,snapshot_id)
    ,
                                                     CONSTRAINT cs_sp_fk_cs FOREIGN KEY (snapshot_id) REFERENCES "ConformanceSnapshots"(id)
) ;

CREATE INDEX cs_sp_id ON "ConformanceSnapshotSpecifications"  (id);
CREATE INDEX cs_sp_fk_cs ON "ConformanceSnapshotSpecifications"  (snapshot_id);

--
-- table `ConformanceSnapshotsysparams`
--

CREATE TABLE "ConformanceSnapshotsysparams" (
                                                sys_id bigint NOT NULL,
                                                snapshot_id bigint NOT NULL,
                                                param_key varchar(254) NOT NULL,
                                                param_value varchar(254) NOT NULL,
                                                PRIMARY KEY (sys_id,snapshot_id,param_key)
    ,
                                                CONSTRAINT cs_sys_param_cs_fk FOREIGN KEY (snapshot_id) REFERENCES "ConformanceSnapshots"(id)
) ;

CREATE INDEX cs_sys_param_cs_sys_idx ON "ConformanceSnapshotsysparams" (sys_id);
CREATE INDEX cs_sys_param_cs_snapshot_idx ON "ConformanceSnapshotsysparams" (snapshot_id);

--
-- table `ConformanceSnapshotsystems`
--

CREATE TABLE "ConformanceSnapshotSystems" (
                                              id bigint NOT NULL,
                                              sname varchar(254) NOT NULL,
                                              fname varchar(254) NOT NULL,
                                              version varchar(254) DEFAULT NULL,
                                              description text,
                                              api_key varchar(254) NOT NULL,
                                              badge_key varchar(254) NOT NULL,
                                              snapshot_id bigint NOT NULL,
                                              PRIMARY KEY (id,snapshot_id)
    ,
                                              CONSTRAINT cs_sys_fk_cs FOREIGN KEY (snapshot_id) REFERENCES "ConformanceSnapshots"(id)
) ;

CREATE INDEX cs_sys_id ON "ConformanceSnapshotSystems" (id);
CREATE INDEX cs_sys_fk_cs ON "ConformanceSnapshotSystems" (snapshot_id);

--
-- table `conformancesnapshottestcases`
--

CREATE TABLE "ConformanceSnapshotTestCases" (
                                                id bigint NOT NULL,
                                                sname varchar(254) NOT NULL,
                                                fname varchar(254) NOT NULL,
                                                version varchar(254) NOT NULL DEFAULT '',
                                                description text,
                                                identifier varchar(254) NOT NULL,
                                                testsuite_order smallint NOT NULL,
                                                is_optional boolean NOT NULL DEFAULT false,
                                                is_disabled boolean NOT NULL DEFAULT false,
                                                tags text,
                                                spec_reference varchar(254) DEFAULT NULL,
                                                spec_description text,
                                                spec_link varchar(254) DEFAULT NULL,
                                                snapshot_id bigint NOT NULL,
                                                PRIMARY KEY (id,snapshot_id)
    ,
                                                CONSTRAINT cs_tc_fk_cs FOREIGN KEY (snapshot_id) REFERENCES "ConformanceSnapshots"(id)
) ;

CREATE INDEX cs_tc_id ON "ConformanceSnapshotTestCases" (id);
CREATE INDEX cs_tc_fk_cs ON "ConformanceSnapshotTestCases" (snapshot_id);

--
-- table `conformancesnapshotTestSuites`
--

CREATE TABLE "ConformanceSnapshotTestSuites" (
                                                 id bigint NOT NULL,
                                                 sname varchar(254) NOT NULL,
                                                 fname varchar(254) NOT NULL,
                                                 version varchar(254) NOT NULL DEFAULT '',
                                                 description text,
                                                 identifier varchar(254) NOT NULL,
                                                 spec_reference varchar(254) DEFAULT NULL,
                                                 spec_description text,
                                                 spec_link varchar(254) DEFAULT NULL,
                                                 snapshot_id bigint NOT NULL,
                                                 PRIMARY KEY (id,snapshot_id)
    ,
                                                 CONSTRAINT cs_ts_fk_cs FOREIGN KEY (snapshot_id) REFERENCES "ConformanceSnapshots"(id)
) ;

CREATE INDEX cs_ts_id ON "ConformanceSnapshotTestSuites" (id);
CREATE INDEX cs_ts_fk_cs ON "ConformanceSnapshotTestSuites" (snapshot_id);

--
-- table `domainParameters`
--

CREATE TABLE "DomainParameters" (
                                    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    name varchar(254) NOT NULL,
                                    description text,
                                    kind varchar(254) NOT NULL,
                                    value text NOT NULL,
                                    domain bigint NOT NULL,
                                    in_tests boolean NOT NULL DEFAULT true,
                                    content_type varchar(254) DEFAULT NULL,
                                    PRIMARY KEY (id),
                                    CONSTRAINT dp_domain_name_idx UNIQUE (name,domain)
    ,
                                    CONSTRAINT dp_fk_domain FOREIGN KEY (domain) REFERENCES "Domains"(id)
) ;

CREATE INDEX dp_idx_domain ON "DomainParameters" (domain);

--
-- table `Endpointsupportstransactions`
--

CREATE TABLE "Endpointsupportstransactions" (
                                                actor bigint NOT NULL,
                                                endpoint varchar(254) NOT NULL,
                                                transaction varchar(254) NOT NULL,
                                                PRIMARY KEY (actor,endpoint,transaction),
                                                CONSTRAINT endsuptra_fk_act FOREIGN KEY (actor) REFERENCES "Actors"(id)
) ;

--
-- table `errortemplates`
--

CREATE TABLE "ErrorTemplates" (
                                  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                  name varchar(255) NOT NULL,
                                  content text,
                                  default_flag boolean NOT NULL DEFAULT false,
                                  description text,
                                  community bigint NOT NULL,
                                  PRIMARY KEY (id)
    ,
                                  CONSTRAINT errtem_fk_com FOREIGN KEY (community) REFERENCES "Communities"(id)
) ;

CREATE INDEX errtem_fk_com ON "ErrorTemplates" (community);

--
-- table `landingpages`
--

CREATE TABLE "LandingPages" (
                                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                name varchar(255) NOT NULL,
                                content text,
                                default_flag boolean NOT NULL DEFAULT false,
                                description text,
                                community bigint NOT NULL,
                                PRIMARY KEY (id)
    ,
                                CONSTRAINT lanpag_fk_com FOREIGN KEY (community) REFERENCES "Communities"(id)
) ;

CREATE INDEX lanpag_fk_com ON "LandingPages" (community);

--
-- table `legalnotices`
--

CREATE TABLE "LegalNotices" (
                                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                name varchar(255) NOT NULL,
                                content text,
                                default_flag boolean NOT NULL DEFAULT false,
                                description text,
                                community bigint NOT NULL,
                                PRIMARY KEY (id)
    ,
                                CONSTRAINT legnot_fk_com FOREIGN KEY (community) REFERENCES "Communities"(id)
) ;

CREATE INDEX legnot_fk_com ON "LegalNotices" (community);

--
-- table `options`
--

CREATE TABLE "Options" (
                           id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                           sname varchar(254) NOT NULL,
                           fname varchar(254) NOT NULL,
                           description text,
                           actor bigint NOT NULL,
                           PRIMARY KEY (id)
    ,
                           CONSTRAINT opt_fk_act FOREIGN KEY (actor) REFERENCES "Actors"(id)
) ;

CREATE INDEX opt_fk_act ON "Options" (actor);

--
-- table `organisationParameters`
--

CREATE TABLE "OrganisationParameters" (
                                          id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                          name varchar(254) NOT NULL,
                                          test_key varchar(254) NOT NULL,
                                          description text,
                                          use varchar(254) NOT NULL,
                                          kind varchar(254) NOT NULL,
                                          admin_only boolean NOT NULL DEFAULT false,
                                          not_for_tests boolean NOT NULL DEFAULT true,
                                          community bigint NOT NULL,
                                          in_exports boolean NOT NULL DEFAULT false,
                                          in_selfreg boolean NOT NULL DEFAULT false,
                                          hidden boolean NOT NULL DEFAULT false,
                                          allowed_values text,
                                          display_order smallint NOT NULL DEFAULT 0,
                                          depends_on varchar(254) DEFAULT NULL,
                                          depends_on_value varchar(254) DEFAULT NULL,
                                          default_value text,
                                          PRIMARY KEY (id)
    ,
                                          CONSTRAINT op_fk_com FOREIGN KEY (community) REFERENCES "Communities"(id)
) ;

CREATE INDEX op_idx_com ON "OrganisationParameters" (community);

--
-- table `organizations`
--

CREATE TABLE "Organizations" (
                                 id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                 sname varchar(254) NOT NULL,
                                 fname varchar(254) NOT NULL,
                                 type smallint NOT NULL,
                                 admin_organization boolean NOT NULL DEFAULT false,
                                 landing_page bigint DEFAULT NULL,
                                 legal_notice bigint DEFAULT NULL,
                                 community bigint NOT NULL,
                                 error_template bigint DEFAULT NULL,
                                 template boolean NOT NULL DEFAULT false,
                                 template_name varchar(254) DEFAULT NULL,
                                 api_key varchar(254) DEFAULT NULL,
                                 updated_on timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP /* ON UPDATE CURRENT_TIMESTAMP */,
                                 PRIMARY KEY (id),
                                 CONSTRAINT org_unique_api_key UNIQUE  (api_key)
    ,
                                 CONSTRAINT org_fk_com FOREIGN KEY (community) REFERENCES "Communities"(id),
                                 CONSTRAINT org_fk_errtem FOREIGN KEY (error_template) REFERENCES "ErrorTemplates"(id),
                                 CONSTRAINT org_fk_lanpag FOREIGN KEY (landing_page) REFERENCES "LandingPages"(id),
                                 CONSTRAINT org_fk_legnot FOREIGN KEY (legal_notice) REFERENCES "LegalNotices"(id)
) ;

CREATE INDEX org_fk_com ON "Organizations" (community);
CREATE INDEX org_fk_lanpag ON "Organizations" (landing_page);
CREATE INDEX org_fk_legnot ON "Organizations" (legal_notice);
CREATE INDEX org_fk_errtem ON "Organizations" (error_template);
CREATE INDEX org_idx_api_key ON "Organizations" (api_key);

INSERT INTO "Organizations" VALUES (0,'Admin organisation','Admin organisation',1,true,NULL,NULL,0,NULL,false,NULL,NULL,CURRENT_TIMESTAMP);
UPDATE "Organizations" SET id = 0;

--
-- table `organisationparametervalues`
--

CREATE TABLE "OrganisationParameterValues" (
                                               organisation bigint NOT NULL,
                                               parameter bigint NOT NULL,
                                               value BYTEA NOT NULL,
                                               content_type varchar(254) DEFAULT NULL,
                                               PRIMARY KEY (organisation,parameter)
    ,
                                               CONSTRAINT opv_fk_org FOREIGN KEY (organisation) REFERENCES "Organizations"(id),
                                               CONSTRAINT opv_fk_par FOREIGN KEY (parameter) REFERENCES "OrganisationParameters"(id)
) ;

CREATE INDEX opv_idx_org ON "OrganisationParameterValues" (organisation);
CREATE INDEX opv_idx_par ON "OrganisationParameterValues" (parameter);

--
-- table `Parameters`
--

CREATE TABLE "Parameters" (
                              id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              name varchar(254) NOT NULL,
                              description text,
                              use varchar(254) NOT NULL,
                              kind varchar(254) NOT NULL,
                              endpoint bigint NOT NULL,
                              admin_only boolean NOT NULL DEFAULT false,
                              not_for_tests boolean NOT NULL DEFAULT false,
                              hidden boolean NOT NULL DEFAULT false,
                              allowed_values text,
                              display_order smallint NOT NULL DEFAULT 0,
                              depends_on varchar(254) DEFAULT NULL,
                              depends_on_value varchar(254) DEFAULT NULL,
                              test_key varchar(254) NOT NULL,
                              default_value text,
                              PRIMARY KEY (id)
    ,
                              CONSTRAINT pa_fk_end FOREIGN KEY (endpoint) REFERENCES "Endpoints"(id)
) ;

CREATE INDEX pa_fk_end ON "Parameters" (endpoint);

--
-- table `ProcessedArchives`
--

CREATE TABLE "ProcessedArchives" (
                                     id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                     archive_hash varchar(254) NOT NULL,
                                     import_time timestamp(0) NOT NULL,
                                     PRIMARY KEY (id),
                                     CONSTRAINT procarch_unique_archive_hash UNIQUE  (archive_hash)
) ;

--
-- table `specificationhasActors`
--

CREATE TABLE "SpecificationHasActors" (
                                          spec_id bigint NOT NULL,
                                          actor_id bigint NOT NULL,
                                          PRIMARY KEY (spec_id,actor_id)
    ,
                                          CONSTRAINT spehact_fk_act FOREIGN KEY (actor_id) REFERENCES "Actors"(id),
                                          CONSTRAINT spehact_fk_spe FOREIGN KEY (spec_id) REFERENCES "Specifications"(id)
) ;

CREATE INDEX spehact_fk_act ON "SpecificationHasActors" (actor_id);

--
-- table `TestSuites`
--

CREATE TABLE "TestSuites" (
                              id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              sname varchar(254) NOT NULL,
                              fname varchar(254) NOT NULL,
                              version varchar(254) NOT NULL,
                              authors varchar(254) DEFAULT NULL,
                              original_date varchar(254) DEFAULT NULL,
                              modification_date varchar(254) DEFAULT NULL,
                              description text,
                              keywords varchar(254) DEFAULT NULL,
                              file_name varchar(255) NOT NULL,
                              has_documentation boolean NOT NULL DEFAULT false,
                              documentation text,
                              identifier varchar(254) NOT NULL,
                              is_hidden boolean NOT NULL DEFAULT false,
                              domain bigint NOT NULL,
                              is_shared boolean NOT NULL DEFAULT false,
                              definition_path varchar(254) DEFAULT NULL,
                              spec_reference varchar(254) DEFAULT NULL,
                              spec_description text,
                              spec_link varchar(254) DEFAULT NULL,
                              PRIMARY KEY (id)
    ,
                              CONSTRAINT ts_fk_domain FOREIGN KEY (domain) REFERENCES "Domains"(id)
) ;

CREATE INDEX ts_idx_domain ON "TestSuites" (domain);

--
-- table `specificationhasTestSuites`
--

CREATE TABLE "SpecificationHasTestSuites" (
                                              spec bigint NOT NULL,
                                              testsuite bigint NOT NULL,
                                              PRIMARY KEY (spec,testsuite)
    ,
                                              CONSTRAINT shts_fk_spec FOREIGN KEY (spec) REFERENCES "Specifications"(id),
                                              CONSTRAINT shts_fk_ts FOREIGN KEY (testsuite) REFERENCES "TestSuites"(id)
) ;

CREATE INDEX shts_spec_idx ON "SpecificationHasTestSuites" (spec);
CREATE INDEX shts_ts_idx ON "SpecificationHasTestSuites" (testsuite);

--
-- table `systemconfigurations`
--

CREATE TABLE "SystemConfigurations" (
                                        name varchar(255) NOT NULL,
                                        parameter text,
                                        description varchar(255) DEFAULT NULL,
                                        PRIMARY KEY (name)
) ;

--
-- SQLINES DEMO *** table `systemconfigurations`
--

INSERT INTO "SystemConfigurations" VALUES ('session_alive_time','3600','session_alive_time');

--
-- table `systems`
--

CREATE TABLE "Systems" (
                           id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                           sname varchar(254) NOT NULL,
                           fname varchar(254) NOT NULL,
                           description text,
                           version varchar(254) DEFAULT NULL,
                           owner bigint NOT NULL,
                           api_key varchar(254) NOT NULL,
                           badge_key varchar(254) NOT NULL,
                           PRIMARY KEY (id),
                           CONSTRAINT sys_unique_badge_key UNIQUE  (badge_key),
                           CONSTRAINT sys_unique_api_key UNIQUE  (api_key)
    ,
                           CONSTRAINT sut_fk_org FOREIGN KEY (owner) REFERENCES "Organizations"(id)
) ;

CREATE INDEX sut_fk_org ON "Systems" (owner);
CREATE INDEX sys_idx_api_key ON "Systems" (api_key);
CREATE INDEX sys_idx_badge_key ON "Systems" (badge_key);

--
-- table `users`
--

CREATE TABLE "Users" (
                         id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 2),
                         name varchar(254) NOT NULL,
                         email varchar(254) NOT NULL,
                         password varchar(254) NOT NULL,
                         role smallint NOT NULL,
                         organization bigint NOT NULL,
                         onetime_password boolean NOT NULL DEFAULT false,
                         sso_uid varchar(254) DEFAULT NULL,
                         sso_email varchar(254) DEFAULT NULL,
                         sso_status smallint NOT NULL DEFAULT '1',
                         PRIMARY KEY (id)
    ,
                         CONSTRAINT use_fk_org FOREIGN KEY (organization) REFERENCES "Organizations"(id)
)  ;

CREATE INDEX users_idx_sso_uid ON "Users" (sso_uid);
CREATE INDEX use_fk_org ON "Users" (organization);

--
-- SQLINES DEMO *** table `Users`
--

INSERT INTO "Users" VALUES (1,'Administrator','admin@itb','$2a$10$uMPniYxO/NJIQiJA/q8kseF5N3KRxXM3bHPnRC0ZyIzvBZ.u6Edha',4,0,true,NULL,NULL,1);

--
-- table `systemhasadmins`
--

CREATE TABLE "SystemHasAdmins" (
                                   sut_id bigint NOT NULL,
                                   user_id bigint NOT NULL,
                                   PRIMARY KEY (sut_id,user_id)
    ,
                                   CONSTRAINT suthadm_fk_sut FOREIGN KEY (sut_id) REFERENCES "Systems"(id),
                                   CONSTRAINT suthadm_fk_use FOREIGN KEY (user_id) REFERENCES "Users"(id)
) ;

CREATE INDEX suthadm_fk_use ON "SystemHasAdmins" (user_id);

--
-- table `systemimplementsActors`
--

CREATE TABLE "SystemImplementsActors" (
                                          sut_id bigint NOT NULL,
                                          spec_id bigint NOT NULL,
                                          actor_id bigint NOT NULL,
                                          PRIMARY KEY (sut_id,spec_id,actor_id)
    ,
                                          CONSTRAINT sutiact_fk_act FOREIGN KEY (actor_id) REFERENCES "Actors"(id),
                                          CONSTRAINT sutiact_fk_spe FOREIGN KEY (spec_id) REFERENCES "Specifications"(id),
                                          CONSTRAINT sutiact_fk_sut FOREIGN KEY (sut_id) REFERENCES "Systems"(id)
) ;

CREATE INDEX sutiact_fk_spe ON "SystemImplementsActors" (spec_id);
CREATE INDEX sutiact_fk_act ON "SystemImplementsActors" (actor_id);

--
-- table `systemimplementsoptions`
--

CREATE TABLE "SystemImplementsOptions" (
                                           sut_id bigint NOT NULL,
                                           option_id bigint NOT NULL,
                                           PRIMARY KEY (sut_id,option_id)
    ,
                                           CONSTRAINT sutiopt_fk_opt FOREIGN KEY (option_id) REFERENCES "Options"(id),
                                           CONSTRAINT sutiopt_fk_sut FOREIGN KEY (sut_id) REFERENCES "Systems"(id)
) ;

CREATE INDEX sutiopt_fk_opt ON "SystemImplementsOptions" (option_id);

--
-- table `systemParameters`
--

CREATE TABLE "SystemParameters" (
                                    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    name varchar(254) NOT NULL,
                                    test_key varchar(254) NOT NULL,
                                    description text,
                                    use varchar(254) NOT NULL,
                                    kind varchar(254) NOT NULL,
                                    admin_only boolean NOT NULL DEFAULT false,
                                    not_for_tests boolean NOT NULL DEFAULT true,
                                    community bigint NOT NULL,
                                    in_exports boolean NOT NULL DEFAULT false,
                                    hidden boolean NOT NULL DEFAULT false,
                                    allowed_values text,
                                    display_order smallint NOT NULL DEFAULT 0,
                                    depends_on varchar(254) DEFAULT NULL,
                                    depends_on_value varchar(254) DEFAULT NULL,
                                    default_value text,
                                    PRIMARY KEY (id)
    ,
                                    CONSTRAINT sy_fk_com FOREIGN KEY (community) REFERENCES "Communities"(id)
) ;

CREATE INDEX sy_idx_com ON "SystemParameters" (community);

--
-- table `systemparametervalues`
--

CREATE TABLE "SystemParameterValues" (
                                         system bigint NOT NULL,
                                         parameter bigint NOT NULL,
                                         value BYTEA NOT NULL,
                                         content_type varchar(254) DEFAULT NULL,
                                         PRIMARY KEY (system,parameter)
    ,
                                         CONSTRAINT spv_fk_par FOREIGN KEY (parameter) REFERENCES "SystemParameters"(id),
                                         CONSTRAINT spv_fk_sys FOREIGN KEY (system) REFERENCES "Systems"(id)
) ;

CREATE INDEX spv_idx_sys ON "SystemParameterValues" (system);
CREATE INDEX spv_idx_par ON "SystemParameterValues" (parameter);

--
-- table `testcasegroups`
--

CREATE TABLE "TestCaseGroups" (
                                  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                  identifier varchar(254) NOT NULL,
                                  name varchar(254) DEFAULT NULL,
                                  description text,
                                  testsuite bigint NOT NULL,
                                  PRIMARY KEY (id)
    ,
                                  CONSTRAINT tcg_fk_testsuite FOREIGN KEY (testsuite) REFERENCES "TestSuites"(id)
) ;

CREATE INDEX tcg_ts_idx ON "TestCaseGroups" (testsuite);

--
-- table `testCases`
--

CREATE TABLE "TestCases" (
                             id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                             sname varchar(254) NOT NULL,
                             fname varchar(254) NOT NULL,
                             version varchar(254) NOT NULL,
                             authors varchar(254) DEFAULT NULL,
                             original_date varchar(254) DEFAULT NULL,
                             modification_date varchar(254) DEFAULT NULL,
                             description text,
                             keywords varchar(254) DEFAULT NULL,
                             type smallint NOT NULL,
                             path varchar(254) NOT NULL,
                             target_Actors varchar(254) DEFAULT NULL,
                             target_options varchar(254) DEFAULT NULL,
                             testsuite_order smallint NOT NULL,
                             has_documentation boolean NOT NULL DEFAULT false,
                             documentation text,
                             identifier varchar(254) NOT NULL,
                             is_optional boolean NOT NULL DEFAULT false,
                             is_disabled boolean NOT NULL DEFAULT false,
                             tags text,
                             spec_reference varchar(254) DEFAULT NULL,
                             spec_description text,
                             spec_link varchar(254) DEFAULT NULL,
                             testcase_group bigint DEFAULT NULL,
                             PRIMARY KEY (id)
    ,
                             CONSTRAINT tc_fk_tcg FOREIGN KEY (testcase_group) REFERENCES "TestCaseGroups"(id)
) ;

CREATE INDEX tc_tcg_idx ON "TestCases" (testcase_group);

--
-- table `testcasecoversoptions`
--

CREATE TABLE "TestCaseCoversOptions" (
                                         testcase bigint NOT NULL,
                                         option bigint NOT NULL,
                                         PRIMARY KEY (testcase,option)
    ,
                                         CONSTRAINT tescovopt_fk_opt FOREIGN KEY (option) REFERENCES "Options"(id),
                                         CONSTRAINT tescovopt_fk_tes FOREIGN KEY (testcase) REFERENCES "TestCases"(id)
) ;

CREATE INDEX tescovopt_fk_opt ON "TestCaseCoversOptions" (option);

--
-- table `testcasehasActors`
--

CREATE TABLE "TestCaseHasActors" (
                                     testcase bigint NOT NULL,
                                     specification bigint NOT NULL,
                                     actor bigint NOT NULL,
                                     sut boolean NOT NULL DEFAULT false,
                                     PRIMARY KEY (testcase,specification,actor)
    ,
                                     CONSTRAINT teshact_fk_act FOREIGN KEY (actor) REFERENCES "Actors"(id),
                                     CONSTRAINT teshact_fk_spe FOREIGN KEY (specification) REFERENCES "Specifications"(id),
                                     CONSTRAINT teshact_fk_tes FOREIGN KEY (testcase) REFERENCES "TestCases"(id)
) ;

CREATE INDEX teshact_fk_spe ON "TestCaseHasActors" (specification);
CREATE INDEX teshact_fk_act ON "TestCaseHasActors" (actor);

--
-- table `testresults`
--

CREATE TABLE "TestResults" (
                               test_session_id varchar(254) NOT NULL,
                               sut_id bigint DEFAULT NULL,
                               sut varchar(254) DEFAULT NULL,
                               organization_id bigint DEFAULT NULL,
                               organization varchar(254) DEFAULT NULL,
                               community_id bigint DEFAULT NULL,
                               community varchar(254) DEFAULT NULL,
                               domain_id bigint DEFAULT NULL,
                               domain varchar(254) DEFAULT NULL,
                               specification_id bigint DEFAULT NULL,
                               specification varchar(254) DEFAULT NULL,
                               actor_id bigint DEFAULT NULL,
                               actor varchar(254) DEFAULT NULL,
                               testsuite_id bigint DEFAULT NULL,
                               testsuite varchar(254) DEFAULT NULL,
                               testcase_id bigint DEFAULT NULL,
                               testcase varchar(254) DEFAULT NULL,
                               result varchar(254) NOT NULL,
                               start_time timestamp(0) NOT NULL DEFAULT '1970-01-01 00:00:01',
                               end_time timestamp(0) NULL DEFAULT NULL,
                               output_message text,
                               PRIMARY KEY (test_session_id)
    ,
                               CONSTRAINT tr_fk_actor FOREIGN KEY (actor_id) REFERENCES "Actors"(id),
                               CONSTRAINT tr_fk_community FOREIGN KEY (community_id) REFERENCES "Communities"(id),
                               CONSTRAINT tr_fk_domain FOREIGN KEY (domain_id) REFERENCES "Domains"(id),
                               CONSTRAINT tr_fk_organization FOREIGN KEY (organization_id) REFERENCES "Organizations"(id),
                               CONSTRAINT tr_fk_specification FOREIGN KEY (specification_id) REFERENCES "Specifications"(id),
                               CONSTRAINT tr_fk_sut FOREIGN KEY (sut_id) REFERENCES "Systems"(id),
                               CONSTRAINT tr_fk_testcase FOREIGN KEY (testcase_id) REFERENCES "TestCases"(id),
                               CONSTRAINT tr_fk_testsuite FOREIGN KEY (testsuite_id) REFERENCES "TestSuites"(id)
) ;

CREATE INDEX tr_idx_sut ON "TestResults" (sut_id);
CREATE INDEX tr_idx_organization ON "TestResults" (organization_id);
CREATE INDEX tr_idx_community ON "TestResults" (community_id);
CREATE INDEX tr_idx_testcase ON "TestResults" (testcase_id);
CREATE INDEX tr_idx_testsuite ON "TestResults" (testsuite_id);
CREATE INDEX tr_idx_actor ON "TestResults" (actor_id);
CREATE INDEX tr_idx_specification ON "TestResults" (specification_id);
CREATE INDEX tr_idx_domain ON "TestResults" (domain_id);

--
-- table `teststepreports`
--

CREATE TABLE "TestStepReports" (
                                   test_session_id varchar(254) NOT NULL,
                                   test_step_id varchar(254) NOT NULL,
                                   result smallint NOT NULL,
                                   report_path varchar(254) NOT NULL,
                                   PRIMARY KEY (test_session_id,test_step_id)
) ;

--
-- table `testsuitehasActors`
--

CREATE TABLE "TestSuiteHasActors" (
                                      testsuite bigint NOT NULL,
                                      actor bigint NOT NULL,
                                      PRIMARY KEY (testsuite,actor)
    ,
                                      CONSTRAINT tessuihact_fk_act FOREIGN KEY (actor) REFERENCES "Actors"(id),
                                      CONSTRAINT tessuihact_fk_tessui FOREIGN KEY (testsuite) REFERENCES "TestSuites"(id)
) ;

CREATE INDEX tessuihact_fk_act ON "TestSuiteHasActors" (actor);

--
-- table `testsuitehastestcases`
--

CREATE TABLE "TestSuiteHasTestCases" (
                                         testsuite bigint NOT NULL,
                                         testcase bigint NOT NULL,
                                         PRIMARY KEY (testsuite,testcase)
    ,
                                         CONSTRAINT tessuihtescas_fk_tescas FOREIGN KEY (testcase) REFERENCES "TestCases"(id),
                                         CONSTRAINT tessuihtescas_fk_tessui FOREIGN KEY (testsuite) REFERENCES "TestSuites"(id)
) ;

CREATE INDEX tessuihtescas_fk_tescas ON "TestSuiteHasTestCases" (testcase);

--
-- table `themes`
--

CREATE TABLE "Themes" (
                          id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 3),
                          theme_key varchar(254) NOT NULL,
                          description text,
                          active boolean NOT NULL DEFAULT false,
                          custom boolean NOT NULL DEFAULT false,
                          separator_title_color varchar(254) NOT NULL,
                          modal_title_color varchar(254) NOT NULL,
                          table_title_color varchar(254) NOT NULL,
                          card_title_color varchar(254) NOT NULL,
                          page_title_color varchar(254) NOT NULL,
                          heading_color varchar(254) NOT NULL,
                          tab_link_color varchar(254) NOT NULL,
                          footer_text_color varchar(254) NOT NULL,
                          header_background_color varchar(254) NOT NULL,
                          header_border_color varchar(254) NOT NULL,
                          header_separator_color varchar(254) NOT NULL,
                          header_logo_path varchar(254) NOT NULL,
                          footer_background_color varchar(254) NOT NULL,
                          footer_border_color varchar(254) NOT NULL,
                          footer_logo_path varchar(254) NOT NULL,
                          footer_logo_display varchar(254) NOT NULL,
                          favicon_path varchar(254) NOT NULL,
                          primary_btn_color VARCHAR(254) NOT NULL,
                          primary_btn_label_color VARCHAR(254) NOT NULL,
                          primary_btn_hover_color VARCHAR(254) NOT NULL,
                          primary_btn_active_color VARCHAR(254) NOT NULL,
                          secondary_btn_color VARCHAR(254) NOT NULL,
                          secondary_btn_label_color VARCHAR(254) NOT NULL,
                          secondary_btn_hover_color VARCHAR(254) NOT NULL,
                          secondary_btn_active_color VARCHAR(254) NOT NULL,
                          PRIMARY KEY (id),
                          CONSTRAINT unique_theme_key UNIQUE  (theme_key)
)  ;

INSERT INTO "Themes" VALUES (1,'ec','European Commission theme.',false,false,'#337ab7','#337ab7','#337ab7','#337ab7','#FFFFFF','#337ab7','#337ab7','#FFFFFF','#0065a2','#074a8b','#FFFFFF','/assets/images/ec.png','#0065a2','#074a8b','/assets/images/gitb.png','inherit','/assets/images/favicon-ec.gif', '#337ab7', '#FFFFFF', '#2b689c', '#296292', '#6c757d', '#FFFFFF' , '#5c636a' , '#565e64'),(2,'gitb','Default GITB theme.',false,false,'#337ab7','#337ab7','#337ab7','#337ab7','#FFFFFF','#337ab7','#337ab7','#FFFFFF','#171717','#CCCCCC','#FFFFFF','/assets/images/gitb.png','#121214','#CCCCCC','/assets/images/gitb.png','none','/assets/images/favicon.png', '#337ab7', '#FFFFFF', '#2b689c', '#296292', '#6c757d', '#FFFFFF' , '#5c636a' , '#565e64');

--
-- table `transactions`
--

CREATE TABLE "Transactions" (
                                sname varchar(254) NOT NULL,
                                fname varchar(254) NOT NULL,
                                description text,
                                domain bigint NOT NULL,
                                PRIMARY KEY (sname)
    ,
                                CONSTRAINT tra_fk_dom FOREIGN KEY (domain) REFERENCES "Domains"(id)
) ;

CREATE INDEX tra_fk_dom ON "Transactions" (domain);

--
-- table `triggers`
--

CREATE TABLE "Triggers" (
                            id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                            name varchar(254) NOT NULL,
                            description text,
                            url varchar(254) NOT NULL,
                            event_type smallint NOT NULL,
                            operation varchar(254) DEFAULT NULL,
                            active boolean NOT NULL DEFAULT true,
                            latest_result_ok boolean DEFAULT NULL,
                            latest_result_output text,
                            community bigint NOT NULL,
                            service_type smallint NOT NULL DEFAULT '1',
                            PRIMARY KEY (id)
    ,
                            CONSTRAINT trigger_fk_community FOREIGN KEY (community) REFERENCES "Communities"(id)
) ;

CREATE INDEX trigger_community_idx ON "Triggers" (community);

--
-- table `triggerdata`
--

CREATE TABLE "TriggerData" (
                               data_type smallint NOT NULL,
                               data_id bigint NOT NULL,
                               trigger bigint NOT NULL,
                               PRIMARY KEY (data_type,data_id,trigger)
    ,
                               CONSTRAINT triggerdata_fk_trigger FOREIGN KEY (trigger) REFERENCES "Triggers"(id)
) ;

CREATE INDEX trigger_data_idx ON "TriggerData" (trigger);
CREATE INDEX trigger_data_id_idx ON "TriggerData" (data_id);
CREATE INDEX trigger_data_id_type_idx ON "TriggerData" (data_id,data_type);

--
-- table `configurations`
--

CREATE TABLE "Configurations" (
                                  system bigint NOT NULL,
                                  parameter bigint NOT NULL,
                                  endpoint bigint NOT NULL,
                                  value BYTEA NOT NULL,
                                  content_type varchar(254) DEFAULT NULL,
                                  PRIMARY KEY (system,parameter,endpoint)
    ,
                                  CONSTRAINT co_fk_end FOREIGN KEY (endpoint) REFERENCES "Endpoints"(id),
                                  CONSTRAINT co_fk_par FOREIGN KEY (parameter) REFERENCES "Parameters"(id),
                                  CONSTRAINT co_fk_sys FOREIGN KEY (system) REFERENCES "Systems"(id)
) ;

CREATE INDEX co_fk_sys ON "Configurations" (system);
CREATE INDEX co_fk_par ON "Configurations" (parameter);
CREATE INDEX co_fk_end ON "Configurations" (endpoint);

--
-- table `conformanceresults`
--

CREATE TABLE "ConformanceResults" (
                                      id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                      sut_id bigint NOT NULL,
                                      spec_id bigint NOT NULL,
                                      actor_id bigint NOT NULL,
                                      test_suite_id bigint NOT NULL,
                                      test_case_id bigint NOT NULL,
                                      test_session_id varchar(254) DEFAULT NULL,
                                      result varchar(254) NOT NULL,
                                      output_message text,
                                      update_time timestamp(0) NULL DEFAULT NULL,
                                      PRIMARY KEY (id),
                                      CONSTRAINT cr_resultinfo_idx UNIQUE  (sut_id,spec_id,actor_id,test_suite_id,test_case_id)
    ,
                                      CONSTRAINT cr_fk_actor FOREIGN KEY (actor_id) REFERENCES "Actors"(id),
                                      CONSTRAINT cr_fk_spec FOREIGN KEY (spec_id) REFERENCES "Specifications"(id),
                                      CONSTRAINT cr_fk_sut FOREIGN KEY (sut_id) REFERENCES "Systems"(id),
                                      CONSTRAINT cr_fk_testcase FOREIGN KEY (test_case_id) REFERENCES "TestCases"(id),
                                      CONSTRAINT cr_fk_testsession FOREIGN KEY (test_session_id) REFERENCES "TestResults"(test_session_id),
                                      CONSTRAINT cr_fk_testsuite FOREIGN KEY (test_suite_id) REFERENCES "TestSuites"(id)
) ;

CREATE INDEX cr_idx_sut ON "ConformanceResults" (sut_id);
CREATE INDEX cr_idx_spec ON "ConformanceResults" (spec_id);
CREATE INDEX cr_idx_actor ON "ConformanceResults" (actor_id);
CREATE INDEX cr_idx_testsuite ON "ConformanceResults" (test_suite_id);
CREATE INDEX cr_idx_testcase ON "ConformanceResults" (test_case_id);
CREATE INDEX cr_idx_testsession ON "ConformanceResults" (test_session_id);

--
-- table `TestInteractions`
--

CREATE TABLE "TestInteractions" (
                                    test_session_id varchar(254) NOT NULL,
                                    test_step_id varchar(254) NOT NULL,
                                    is_admin boolean NOT NULL DEFAULT false,
                                    tpl bytea NOT NULL,
                                    created_on timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    PRIMARY KEY (test_session_id,test_step_id),
                                    CONSTRAINT ti_fk_tr FOREIGN KEY (test_session_id) REFERENCES "TestResults"(test_session_id)
) ;

--
-- table `testresultdefinitions`
--

CREATE TABLE "TestResultDefinitions" (
                                         test_session_id varchar(254) NOT NULL,
                                         tpl text NOT NULL,
                                         PRIMARY KEY (test_session_id),
                                         CONSTRAINT trd_fk_tr FOREIGN KEY (test_session_id) REFERENCES "TestResults"(test_session_id)
) ;

--
-- table `conformancesnapshotresults`
--

CREATE TABLE "ConformanceSnapshotResults" (
                                              id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                              organization_id bigint NOT NULL,
                                              sut_id bigint NOT NULL,
                                              domain_id bigint NOT NULL,
                                              spec_group_id bigint DEFAULT NULL,
                                              spec_id bigint NOT NULL,
                                              actor_id bigint NOT NULL,
                                              test_suite_id bigint NOT NULL,
                                              test_case_id bigint NOT NULL,
                                              test_session_id varchar(254) DEFAULT NULL,
                                              result varchar(254) NOT NULL,
                                              output_message text,
                                              update_time timestamp(0) NULL DEFAULT NULL,
                                              snapshot_id bigint NOT NULL,
                                              PRIMARY KEY (id)
    ,
                                              CONSTRAINT crs_fk_snapshot FOREIGN KEY (snapshot_id) REFERENCES "ConformanceSnapshots"(id),
                                              CONSTRAINT crs_fk_testsession FOREIGN KEY (test_session_id) REFERENCES "TestResults"(test_session_id)
) ;

CREATE INDEX csr_idx_org ON "ConformanceSnapshotResults" (organization_id);
CREATE INDEX csr_idx_sut ON "ConformanceSnapshotResults" (sut_id);
CREATE INDEX csr_idx_domain ON "ConformanceSnapshotResults" (domain_id);
CREATE INDEX csr_idx_spec ON "ConformanceSnapshotResults" (spec_id);
CREATE INDEX csr_idx_actor ON "ConformanceSnapshotResults" (actor_id);
CREATE INDEX csr_idx_testsuite ON "ConformanceSnapshotResults" (test_suite_id);
CREATE INDEX csr_idx_testcase ON "ConformanceSnapshotResults" (test_case_id);
CREATE INDEX csr_idx_testsession ON "ConformanceSnapshotResults" (test_session_id);
CREATE INDEX csr_idx_snapshot ON "ConformanceSnapshotResults" (snapshot_id);

--
-- table `communityreportsettings`
--

CREATE TABLE "CommunityReportSettings" (
                                           report_type smallint NOT NULL,
                                           sign_pdf boolean NOT NULL DEFAULT false,
                                           custom_pdf boolean NOT NULL DEFAULT false,
                                           custom_pdf_with_custom_xml boolean NOT NULL DEFAULT false,
                                           custom_pdf_service varchar(255) DEFAULT NULL,
                                           community bigint NOT NULL,
                                           PRIMARY KEY (report_type,community)
    ,
                                           CONSTRAINT crs_fk_com FOREIGN KEY (community) REFERENCES "Communities"(id)
) ;

CREATE INDEX crs_fk_com ON "CommunityReportSettings" (community);

--
-- table `triggerfireexpressions`
--

CREATE TABLE "TriggerFireExpressions" (
                                          id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 113),
                                          expression varchar(1024) NOT NULL,
                                          expression_type smallint NOT NULL,
                                          not_match boolean NOT NULL DEFAULT false,
                                          trigger bigint NOT NULL,
                                          PRIMARY KEY (id)
    ,
                                          CONSTRAINT tfe_fk_trigger FOREIGN KEY (trigger) REFERENCES "Triggers"(id)
)  ;

CREATE INDEX tfe_trigger_idx ON "TriggerFireExpressions" (trigger);

--
-- table `conformancesnapshottestcasegroups`
--

CREATE TABLE "ConformanceSnapshotTestCaseGroups" (
                                                     id bigint NOT NULL,
                                                     identifier varchar(254) NOT NULL,
                                                     name varchar(254) DEFAULT NULL,
                                                     description text,
                                                     snapshot_id bigint NOT NULL,
                                                     PRIMARY KEY (id,snapshot_id)
    ,
                                                     CONSTRAINT cs_tcg_fk_cs FOREIGN KEY (snapshot_id) REFERENCES "ConformanceSnapshots"(id)
) ;

CREATE INDEX cs_tcg_id ON "ConformanceSnapshotTestCaseGroups" (id);
CREATE INDEX cs_tcg_fk_cs_idx ON "ConformanceSnapshotTestCaseGroups" (snapshot_id);

--
-- table `schema_version`
--

CREATE TABLE schema_version (
                                installed_rank int NOT NULL,
                                version varchar(50) DEFAULT NULL,
                                description varchar(200) NOT NULL,
                                type varchar(20) NOT NULL,
                                script varchar(1000) NOT NULL,
                                checksum int DEFAULT NULL,
                                installed_by varchar(100) NOT NULL,
                                installed_on timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                execution_time int NOT NULL,
                                success smallint NOT NULL,
                                PRIMARY KEY (installed_rank)
) ;

CREATE INDEX schema_version_s_idx ON "schema_version" (success);

INSERT INTO schema_version VALUES
                               (1,'1','Base DB for GITB v1.1.0','SQL','V1__Base_DB_for_GITB_v1.1.0.sql',-73768430,'gitb',CURRENT_TIMESTAMP,1,1),
                               (2,'2','Adapt unique index for test suite','SQL','V2__Adapt_unique_index_for_test_suite.sql',499898989,'gitb',CURRENT_TIMESTAMP,1,1),
                               (3,'3','Link Actors to specification','SQL','V3__Link_Actors_to_specification.sql',831675058,'gitb',CURRENT_TIMESTAMP,1,1),
                               (4,'4','Add test suite id to test case','SQL','V4__Add_test_suite_id_to_test_case.sql',-358339782,'gitb',CURRENT_TIMESTAMP,1,1),
                               (5,'5','Add relations to test results','SQL','V5__Add_relations_to_test_results.sql',878432760,'gitb',CURRENT_TIMESTAMP,1,1),
                               (6,'6','Add domain configuration','SQL','V6__Add_domain_configuration.sql',-1713576226,'gitb',CURRENT_TIMESTAMP,1,1),
                               (7,'7','Add conformance results','SQL','V7__Add_conformance_results.sql',-1397307750,'gitb',CURRENT_TIMESTAMP,1,1),
                               (8,'8','Add community support email','SQL','V8__Add_community_support_email.sql',360522625,'gitb',CURRENT_TIMESTAMP,1,1),
                               (9,'9','Add support for onetime passwords','SQL','V9__Add_support_for_onetime_passwords.sql',-116732750,'gitb',CURRENT_TIMESTAMP,1,1),
                               (10,'10','Add support for default Actors and actor ordering','SQL','V10__Add_support_for default_Actors_and_actor_ordering.sql',-1131698601,'gitb',CURRENT_TIMESTAMP,1,1),
                               (11,'11','Default actor set by default','SQL','V11__Default_actor_set_by_default.sql',-1035269397,'gitb',CURRENT_TIMESTAMP,1,1),
                               (12,'12','Add error templates','SQL','V12__Add_error_templates.sql',-925061201,'gitb',CURRENT_TIMESTAMP,48,1),
                               (13,'13','Add conformance certificates','SQL','V13__Add_conformance_certificates.sql',41367143,'gitb',CURRENT_TIMESTAMP,1,1),
                               (14,'14','Add test suite file name','SQL','V14__Add_test_suite_file_name.sql',740462335,'gitb',CURRENT_TIMESTAMP,1,1),
                               (15,'15','Add test case order','SQL','V15__Add_test_case_order.sql',691562092,'gitb',CURRENT_TIMESTAMP,1,1),
                               (16,'16','Add actor role to testcasehasActors','SQL','V16__Add_actor_role_to_testcasehasActors.sql',2095364803,'gitb',CURRENT_TIMESTAMP,1,1),
                               (17,'17','Add sso info to users','SQL','V17__Add_sso_info_to_users.sql',1549358344,'gitb',CURRENT_TIMESTAMP,1,1),
                               (18,'18','Self registration for Communities','SQL','V18__Self_registration_for_Communities.sql',-1831753832,'gitb',CURRENT_TIMESTAMP,1,1),
                               (19,'19','Public organisation templates','SQL','V19__Public_organisation_templates.sql',-1939653405,'gitb',CURRENT_TIMESTAMP,1,1),
                               (20,'20','Configuration parameter extensions','SQL','V20__Configuration_parameter_extensions.sql',-1035911279,'gitb',CURRENT_TIMESTAMP,1,1),
                               (21,'21','Organisation and system properties','SQL','V21__Organisation_and_system_properties.sql',183476512,'gitb',CURRENT_TIMESTAMP,1,1),
                               (22,'22','Convert blobs to BYTEAs','SQL','V22__Convert_blobs_to_BYTEAs.sql',-970297921,'gitb',CURRENT_TIMESTAMP,1,1),
                               (23,'23','Custom properties exportable','SQL','V23__Custom_properties_exportable.sql',1153276711,'gitb',CURRENT_TIMESTAMP,1,1),
                               (24,'24','Update collation for unique text columns','SQL','V24__Update_collation_for_unique_text_columns.sql',-2001633495,'gitb',CURRENT_TIMESTAMP,1,1),
                               (25,'25','Custom community labels','SQL','V25__Custom_community_labels.sql',-2003050903,'gitb',CURRENT_TIMESTAMP,1,1),
                               (26,'26','Custom community labels casing','SQL','V26__Custom_community_labels_casing.sql',-393528537,'gitb',CURRENT_TIMESTAMP,1,1),
                               (27,'27','Add support for hidden Actors','SQL','V27__Add_support_for_hidden_Actors.sql',-87825788,'gitb',CURRENT_TIMESTAMP,1,1),
                               (28,'28','Self registration notifications','SQL','V28__Self_registration_notifications.sql',840077450,'gitb',CURRENT_TIMESTAMP,1,1),
                               (29,'29','Add support for hidden Specifications','SQL','V29__Add_support_for_hidden_Specifications.sql',-432389468,'gitb',CURRENT_TIMESTAMP,1,1),
                               (30,'30','Community descriptions','SQL','V30__Community_descriptions.sql',1709179894,'gitb',CURRENT_TIMESTAMP,1,1),
                               (31,'31','Organisation properties in selfreg','SQL','V31__Organisation_properties_in_selfreg.sql',254738404,'gitb',CURRENT_TIMESTAMP,1,1),
                               (32,'32','Drop unused specification columns','SQL','V32__Drop_unused_specification_columns.sql',1746644882,'gitb',CURRENT_TIMESTAMP,1,1),
                               (33,'33','Test suite and test case documentation','SQL','V33__Test_suite_and_test_case_documentation.sql',82696514,'gitb',CURRENT_TIMESTAMP,1,1),
                               (34,'34','Community selfregistration restrictions','SQL','V34__Community_selfregistration_restrictions.sql',-343788971,'gitb',CURRENT_TIMESTAMP,1,1),
                               (35,'35','Remove unlinked configurations','SQL','V35__Remove_unlinked_configurations.sql',-1308926168,'gitb',CURRENT_TIMESTAMP,1,1),
                               (36,'36','Add FKs','SQL','V36__Add_FKs.sql',-1151636041,'gitb',CURRENT_TIMESTAMP,1,1),
                               (37,'37','Custom self registration token help text','SQL','V37__Custom_self_registration_token_help_text.sql',1570543424,'gitb',CURRENT_TIMESTAMP,1,1),
                               (38,'38','Consider test suite and test case ids','SQL','V38__Consider_test_suite_and_test_case_ids.sql',1771261602,'gitb',CURRENT_TIMESTAMP,1,1),
                               (39,'39','Event triggers','SQL','V39__Event_triggers.sql',-1158885277,'gitb',CURRENT_TIMESTAMP,1,1),
                               (40,'40','Custom properties hidden','SQL','V40__Custom_properties_hidden.sql',1141392030,'gitb',CURRENT_TIMESTAMP,1,1),
                               (41,'41','self registration requirements','SQL','V41__self_registration_requirements.sql',1013755218,'gitb',CURRENT_TIMESTAMP,1,1),
                               (42,'42','Property predefined values','SQL','V42__Property_predefined_values.sql',1422166555,'gitb',CURRENT_TIMESTAMP,1,1),
                               (43,'43','Property dependencies and ordering','SQL','V43__Property_dependencies_and_ordering.sql',-1143442651,'gitb',CURRENT_TIMESTAMP,1,1),
                               (44,'44','Certificate download by organisation users','SQL','V44__Certificate_download_by_organisation_users.sql',1813433776,'gitb',CURRENT_TIMESTAMP,1,1),
                               (45,'45','Community permissions','SQL','V45__Community_permissions.sql',-285370422,'gitb',CURRENT_TIMESTAMP,1,1),
                               (46,'46','Domain Parameters not in tests','SQL','V46__Domain_Parameters_not_in_tests.sql',1010371115,'gitb',CURRENT_TIMESTAMP,1,1),
                               (47,'47','Community permissions linked to tests','SQL','V47__Community_permissions_linked_to_tests.sql',1459168953,'gitb',CURRENT_TIMESTAMP,1,1),
                               (48,'48','Test session output','SQL','V48__Test_session_output.sql',2112471697,'gitb',CURRENT_TIMESTAMP,1,1),
                               (49,'49','Hidden test suites','SQL','V49__Hidden_test_suites.sql',-1686810958,'gitb',CURRENT_TIMESTAMP,1,1),
                               (50,'50','Force password change for default users','SQL','V50__Force_password_change_for_default_users.sql',-324785039,'gitb',CURRENT_TIMESTAMP,1,1),
                               (51,'51','Update character sets and collations','SQL','V51__Update_character_sets_and_collations.sql',1922528259,'gitb',CURRENT_TIMESTAMP,1,1),
                               (52,'52','Enable secrets verification','SQL','V52__Enable_secrets_verification.sql',-1713227413,'gitb',CURRENT_TIMESTAMP,1,1),
                               (53,'53','Encrypt secrets at rest','JDBC','db.migration.default.V53__Encrypt_secrets_at_rest',NULL,'gitb',CURRENT_TIMESTAMP,1,1),
                               (54,'54','Conformance result update time','SQL','V54__Conformance_result_update_time.sql',1260997359,'gitb',CURRENT_TIMESTAMP,1,1),
                               (55,'55','Attachments','SQL','V55__Attachments.sql',-1574527087,'gitb',CURRENT_TIMESTAMP,1,1),
                               (56,'56','Externalize attachments','JDBC','db.migration.default.V56__Externalize_attachments',NULL,'gitb',CURRENT_TIMESTAMP,3,1),
                               (57,'57','API keys for organisation and system','SQL','V57__API_keys_for_organisation_and_system.sql',-601544797,'gitb',CURRENT_TIMESTAMP,1,1),
                               (58,'58','automation api option for community','SQL','V58__automation_api_option_for_community.sql',1439458830,'gitb',CURRENT_TIMESTAMP,1,1),
                               (59,'59','API key for Actors','SQL','V59__API_key_for_Actors.sql',1002432170,'gitb',CURRENT_TIMESTAMP,1,1),
                               (60,'60','Set actor api keys','JDBC','db.migration.default.V60__Set_actor_api_keys',NULL,'gitb',CURRENT_TIMESTAMP,1,1),
                               (61,'61','API key for Actors not null','SQL','V61__API_key_for_Actors_not_null.sql',-8356564,'gitb',CURRENT_TIMESTAMP,1,1),
                               (62,'62','API key for Specifications','SQL','V62__API_key_for_Specifications.sql',1779994973,'gitb',CURRENT_TIMESTAMP,1,1),
                               (63,'63','Set specification api keys','JDBC','db.migration.default.V63__Set_specification_api_keys',NULL,'gitb',CURRENT_TIMESTAMP,1,1),
                               (64,'64','API key for Specifications not null','SQL','V64__API_key_for_Specifications_not_null.sql',140455792,'gitb',CURRENT_TIMESTAMP,1,1),
                               (65,'65','API key for Communities','SQL','V65__API_key_for_Communities.sql',-809042688,'gitb',CURRENT_TIMESTAMP,1,1),
                               (66,'66','Set community api keys','JDBC','db.migration.default.V66__Set_community_api_keys',NULL,'gitb',CURRENT_TIMESTAMP,1,1),
                               (67,'67','API key for commuities not null','SQL','V67__API_key_for_commuities_not_null.sql',113682536,'gitb',CURRENT_TIMESTAMP,1,1),
                               (68,'68','Trigger service types','SQL','V68__Trigger_service_types.sql',1463727509,'gitb',CURRENT_TIMESTAMP,1,1),
                               (69,'69','Statement parameter names','SQL','V69__Statement_parameter_names.sql',1214434879,'gitb',CURRENT_TIMESTAMP,1,1),
                               (70,'70','Parameter default values','SQL','V70__Parameter_default_values.sql',-1051843489,'gitb',CURRENT_TIMESTAMP,1,1),
                               (71,'71','Community resources','SQL','V71__Community_resources.sql',-425769711,'gitb',CURRENT_TIMESTAMP,1,1),
                               (72,'72','Test result definitions','SQL','V72__Test_result_definitions.sql',60376263,'gitb',CURRENT_TIMESTAMP,1,1),
                               (73,'73','Shared test suites','SQL','V73__Shared_test_suites.sql',1945282748,'gitb',CURRENT_TIMESTAMP,1,1),
                               (74,'74','Decouple test suite folders from specs','JDBC','db.migration.default.V74__Decouple_test_suite_folders_from_specs',NULL,'gitb',CURRENT_TIMESTAMP,1,1),
                               (75,'75','Specification groups','SQL','V75__Specification_groups.sql',-1021339309,'gitb',CURRENT_TIMESTAMP,1,1),
                               (76,'76','Optional system version','SQL','V76__Optional_system_version.sql',9240850,'gitb',CURRENT_TIMESTAMP,1,1),
                               (77,'77','Specification ordering','SQL','V77__Specification_ordering.sql',149597996,'gitb',CURRENT_TIMESTAMP,1,1),
                               (78,'78','Optional and disabled test cases','SQL','V78__Optional_and_disabled_test_cases.sql',-1570809626,'gitb',CURRENT_TIMESTAMP,1,1),
                               (79,'79','Test case tags','SQL','V79__Test_case_tags.sql',1630356962,'gitb',CURRENT_TIMESTAMP,1,1),
                               (80,'80','System configurations long values','SQL','V80__System_configurations_long_values.sql',-2143276474,'gitb',CURRENT_TIMESTAMP,1,1),
                               (81,'81','Optional title in conformance certificate','SQL','V81__Optional_title_in_conformance_certificate.sql',-1139596533,'gitb',CURRENT_TIMESTAMP,1,1),
                               (82,'82','Conformance status snapshots','SQL','V82__Conformance_status_snapshots.sql',-18038241,'gitb',CURRENT_TIMESTAMP,1,1),
                               (83,'83','Conformance badges','SQL','V83__Conformance_badges.sql',183300382,'gitb',CURRENT_TIMESTAMP,1,1),
                               (84,'84','Set system badge keys','JDBC','db.migration.default.V84__Set_system_badge_keys',NULL,'gitb',CURRENT_TIMESTAMP,1,1),
                               (85,'85','Update snapshot badge keys','SQL','V85__Update_snapshot_badge_keys.sql',1119878505,'gitb',CURRENT_TIMESTAMP,1,1),
                               (86,'86','Set conformance snapshot api keys','JDBC','db.migration.default.V86__Set_conformance_snapshot_api_keys',NULL,'gitb',CURRENT_TIMESTAMP,1,1),
                               (87,'87','Snapshot api key not null','SQL','V87__Snapshot_api_key_not_null.sql',-1008012839,'gitb',CURRENT_TIMESTAMP,1,1),
                               (88,'88','Themes','SQL','V88__Themes.sql',-1093466762,'gitb',CURRENT_TIMESTAMP,1,1),
                               (89,'89','Sandbox archive hashes','SQL','V89__Sandbox_archive_hashes.sql',592072697,'gitb',CURRENT_TIMESTAMP,1,1),
                               (90,'90','Optional conformance certificate page numbers','SQL','V90__Optional_conformance_certificate_page_numbers.sql',-1783357143,'gitb',CURRENT_TIMESTAMP,1,1),
                               (91,'91','Delete sample user accounts','SQL','V91__Delete_sample_user_accounts.sql',1645928495,'gitb',CURRENT_TIMESTAMP,1,1),
                               (92,'92','Organisation last update timestamp','SQL','V92__Organisation_last_update_timestamp.sql',968863300,'gitb',CURRENT_TIMESTAMP,1,1),
                               (93,'93','Persistent test session user interactions','SQL','V93__Persistent_test_session_user_interactions.sql',2061585440,'gitb',CURRENT_TIMESTAMP,1,1),
                               (94,'94','Pending interaction notifications','SQL','V94__Pending_interaction_notifications.sql',-746890738,'gitb',CURRENT_TIMESTAMP,1,1),
                               (95,'95','Test suite specification references','SQL','V95__Test_suite_specification_references.sql',-2120813180,'gitb',CURRENT_TIMESTAMP,1,1),
                               (96,'96','Public conformance snapshots','SQL','V96__Public_conformance_snapshots.sql',-2091534627,'gitb',CURRENT_TIMESTAMP,1,1),
                               (97,'97','Extended conformance snapshot data','SQL','V97__Extended_conformance_snapshot_data.sql',1650461432,'gitb',CURRENT_TIMESTAMP,1,1),
                               (98,'98','Conformance overview certificates','SQL','V98__Conformance_overview_certificates.sql',-458804731,'gitb',CURRENT_TIMESTAMP,1,1),
                               (99,'99','SUT flag for snapshot Actors','SQL','V99__SUT_flag_for_snapshot_Actors.sql',-154362525,'gitb',CURRENT_TIMESTAMP,1,1),
                               (100,'100','Remove builtin test organisation','SQL','V100__Remove_builtin_test_organisation.sql',-278512833,'gitb',CURRENT_TIMESTAMP,1,1),
                               (101,'101','System version in snapshots','SQL','V101__System_version_in_snapshots.sql',-540628724,'gitb',CURRENT_TIMESTAMP,1,1),
                               (102,'102','Test case and suite versions in snapshots','SQL','V102__Test_case_and_suite_versions_in_snapshots.sql',1541639576,'gitb',CURRENT_TIMESTAMP,1,1),
                               (103,'103','Domain API keys','SQL','V103__Domain_API_keys.sql',1141368,'gitb',CURRENT_TIMESTAMP,1,1),
                               (104,'104','Set domain api keys','JDBC','db.migration.default.V104__Set_domain_api_keys',NULL,'gitb',CURRENT_TIMESTAMP,1,1),
                               (105,'105','Domain API keys not null','SQL','V105__Domain_API_keys_not_null.sql',223332356,'gitb',CURRENT_TIMESTAMP,1,1),
                               (106,'106','Set system api keys','JDBC','db.migration.default.V106__Set_system_api_keys',NULL,'gitb',CURRENT_TIMESTAMP,1,1),
                               (107,'107','System API keys not null','SQL','V107__System_API_keys_not_null.sql',1208983549,'gitb',CURRENT_TIMESTAMP,1,1),
                               (108,'108','Set system api keys in snapshots','JDBC','db.migration.default.V108__Set_system_api_keys_in_snapshots',NULL,'gitb',CURRENT_TIMESTAMP,1,1),
                               (109,'109','System API keys in snapshots not null','SQL','V109__System_API_keys_in_snapshots_not_null.sql',867885826,'gitb',CURRENT_TIMESTAMP,1,1),
                               (110,'110','Use environment variables if no active theme set','JDBC','db.migration.default.V110__Use_environment_variables_if_no_active_theme_set',NULL,'gitb',CURRENT_TIMESTAMP,1,1),
                               (111,'111','Button theming','SQL','V111__Button_theming.sql',-44417178,'gitb',CURRENT_TIMESTAMP,1,1),
                               (112,'112','Delete stored default master password', 'SQL', 'V112__Delete_stored_default_master_password.sql', -215143895, 'gitb', CURRENT_TIMESTAMP, 1, 1),
                               (113,'113','Specification group API keys', 'SQL', 'V113__Specification_group_API_keys.sql', -277162903, 'gitb', CURRENT_TIMESTAMP, 1, 1),
                               (114,'114','Set specification group api keys', 'JDBC', 'db.migration.default.V114__Set_specification_group_api_keys', NULL, 'gitb', CURRENT_TIMESTAMP, 1, 1),
                               (115,'115','Specification group API keys not null', 'SQL', 'V115__Specification_group_API_keys_not_null.sql', 416615516, 'gitb', CURRENT_TIMESTAMP, 1, 1),
                               (116,'116','Report settings', 'SQL', 'V116__Report_settings.sql', -14344712, 'gitb', CURRENT_TIMESTAMP, 1, 1),
                               (117,'117','XML report metadata', 'SQL', 'V117__XML_report_metadata.sql', -2009734919, 'gitb', CURRENT_TIMESTAMP, 1, 1),
                               (118,'118','Trigger fire expressions', 'SQL', 'V118__Trigger_fire_expressions.sql', -763600425, 'gitb', CURRENT_TIMESTAMP, 1, 1),
                               (119,'119','Test case groups', 'SQL', 'V119__Test_case_groups.sql', -319546087, 'gitb', CURRENT_TIMESTAMP, 1, 1),
                               (120,'120','TPL storage as MEDIUMBLOB','SQL','V120__TPL_storage_as_MEDIUMBLOB.sql',1107412605,'gitb',CURRENT_TIMESTAMP, 1, 1),
                               (121,'121','Allow readonly community view for users','SQL','V121__Allow_readonly_community_view_for_users.sql',-1480519436,'gitb',CURRENT_TIMESTAMP, 1, 1);
